Repository software-students-fall2021/project-setup-dyor, pull requests merged in 2021-12, with the labels that each got.

#188 Resolved a failing test
  back-end/package-lock.json
  back-end/package.json
  back-end/routes/coinPriceTimeSeries.js
  back-end/test/coinPriceTimeSeriesTest.js
  back-end/test/routes.test.js
Labels: bug

#190 Exchange rate fix
  back-end/controllers/users.js
  back-end/data.js
  back-end/models/users.js
  back-end/news.rest
  back-end/refreshSocials/refreshNews.js
  back-end/routes/getNews.js
  back-end/routes/users.js
  front-end/src/components/PortfolioTable/PortfolioTable.jsx
  front-end/src/containers/LandingPage/LandingPage.jsx
  front-end/src/containers/LoginPage/LoginPage.jsx
  front-end/src/containers/SettingsPage/SettingsPage.jsx
Labels: enhancement

#197 setting up user routes tests using mongodb-memory-server
  back-end/controllers/users.js
  back-end/package-lock.json
  back-end/package.json
  back-end/passport.js
  back-end/routes/users.js
  back-end/test/mockDB.js
  back-end/test/users.test.js
Labels: enhancement

#199 Debugged issues with userRoutes test and also added more test
  back-end/routes/users.js
  back-end/test/mockDB.js
  back-end/test/routes.test.js
  back-end/test/users.test.js
  back-end/test/usersTest.js
Labels: enhancement

#200 Compile front-end and back-ed together
  back-end/package.json
Labels: task

#201 Readme roles update
  README.md
Labels: documentation

#204 Fix failing news update
  back-end/app.js
  back-end/refreshSocials/refreshNews.js
Labels: bug

#209 fix reddit and scheduler bug
  back-end/app.js
  back-end/refreshSocials/refreshReddit.js
  back-end/routes/getReddit.js
  back-end/routes/users.js
  back-end/test/getSocialsTest.js
  front-end/src/components/NFATable/NFATable.jsx
  front-end/src/components/Search/Search.js
  front-end/src/containers/PortfolioPage/PortfolioPage.jsx
  package-lock.json
Labels: bug

#210 Update README.md
  README.md
Labels: documentation

#217 fix Shiba subreddit
  back-end/refreshSocials/refreshReddit.js
Labels: bug

#218 error handling for refresh socials
  back-end/refreshSocials/refreshNews.js
  back-end/refreshSocials/refreshReddit.js
  back-end/refreshSocials/refreshTwitter.js
Labels: enhancement
