Repository software-students-fall2021/project-setup-dyor, pull requests merged in 2021-11, with the labels that each got.

#96 Refactored user data so that it is accessible from express server
  back-end/app.js
  back-end/package-lock.json
  back-end/package.json
  back-end/routes/userData.js
  back-end/server.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/containers/PortfolioPage/PortfolioPage.jsx
  package-lock.json
Labels: task

#97 Refactor front-end to call back-end news api
  back-end/app.js
  back-end/data.js
  back-end/package-lock.json
  back-end/package.json
  back-end/routes/getNews.js
  back-end/routes/userData.js
  back-end/server.js
  front-end/src/components/NewsTile/newsTile.jsx
  front-end/src/containers/Dashboard/Dashboard.jsx
  front-end/src/containers/HelpCenterPage/HelpCenterPage.jsx
  front-end/src/containers/NewsPage/newsPage.jsx
Labels: enhancement, task

#99 Refactor news api route
  back-end/app.js
  back-end/routes/getNews.js
  back-end/routes/userData.js
  front-end/src/components/NewsTile/newsTile.jsx
  front-end/src/containers/Dashboard/Dashboard.jsx
  front-end/src/containers/NewsPage/newsPage.jsx
Labels: enhancement

#102 Refactoring wordcloud and nfa files for backend
  front-end/src/components/WordCloud/WordCloud.jsx
  front-end/src/containers/NFA/NFA.jsx
Labels: enhancement

#110 Add tests for news and social media
  back-end/.babelrc
  back-end/mocha-setup.js
  back-end/package-lock.json
  back-end/package.json
  back-end/routes/getNews.js
  back-end/routes/getSocials.js
  back-end/tests/getNews.test.js
  back-end/tests/getSocials.test.js
Labels: enhancement

#114 change api back to twitter api
  back-end/data.js
  back-end/package-lock.json
  back-end/routes/getNews.js
  back-end/routes/getSocials.js
  back-end/test/coinLabel.test.js
  back-end/test/coinPresentPriceAndChange.test.js
  back-end/test/getNews.test.js
  back-end/test/getSocials.test.js
  back-end/test/userAssetData.test.js
Labels: bug

#123 Get posts from reddit and news api
  back-end/data.js
  back-end/public/socials/BTC.json
  back-end/public/socials/DOGE.json
  back-end/public/socials/DOT.json
  back-end/public/socials/ETH.json
  back-end/public/socials/LTC.json
  back-end/public/socials/SHIB.json
  back-end/routes/getNews.js
  back-end/routes/getSocials.js
  books.json
  front-end/public/default_crypto.jpeg
  front-end/src/components/Article/article.jsx
  front-end/src/components/NFASocialMedia/NFASocialMedia.jsx
  front-end/src/components/NFASocialMediaTile/NFASocialMedia.css
  front-end/src/components/NFASocialMediaTile/NFASocialMediaTile.js
  front-end/src/components/NewsTile/newsTile.css
  front-end/src/components/NewsTile/newsTile.jsx
  front-end/src/containers/Dashboard/Dashboard.jsx
  front-end/src/containers/LandingPage/LandingPage.jsx
  front-end/src/containers/NFA/NFA.jsx
  front-end/src/containers/NFA/NFA.module.css
  front-end/src/containers/NewsPage/newsPage.jsx
Labels: enhancement

#132 Add new unit tests or new api calls
  back-end/public/socials/BTC.json
  back-end/public/socials/SHIB.json
  back-end/routes/getNews.js
  back-end/routes/getSocials.js
  back-end/test/getNews.test.js
  back-end/test/getSocials.test.js
Labels: enhancement

#140 Access news and socials from database
  back-end/app.js
  back-end/news.rest
  back-end/package-lock.json
  back-end/package.json
  back-end/public/socials/ADA.json
  back-end/public/socials/BTC.json
  back-end/public/socials/DOGE.json
  back-end/public/socials/DOT.json
  back-end/public/socials/ETH.json
  back-end/public/socials/LTC.json
  back-end/public/socials/SHIB.json
  back-end/public/socials/SOL.json
  back-end/public/socials/crypto.json
  back-end/routes/getNews.js
  back-end/routes/getReddit.js
  back-end/routes/getSocials.js
  back-end/routes/getTwitter.js
  back-end/routes/nfa.js
  back-end/schemas/newsModel.js
  back-end/schemas/redditModel.js
  back-end/schemas/tweetsModel.js
  back-end/server.js
  front-end/src/components/NewsTile/newsTile.jsx
  front-end/src/containers/Dashboard/Dashboard.jsx
  front-end/src/containers/HelpCenterPage/HelpCenterPage.css
  front-end/src/containers/HelpCenterPage/HelpCenterPage.jsx
  front-end/src/containers/LandingPage/LandingPage.jsx
  front-end/src/containers/LoginPage/LoginPage.jsx
  front-end/src/containers/LoginPage/LoginPage.module.css
  front-end/src/containers/NFA/NFA.jsx
  front-end/src/containers/NewsPage/newsPage.jsx
  front-end/src/containers/SettingsPage/SettingsPage.jsx
  front-end/src/containers/SignupPage/SignupPage.jsx
  front-end/src/containers/SignupPage/SignupPage.module.css
Labels: enhancement

#143 Added trigger to refresh news, reddit and twitter. Added back button to loginPage
  back-end/app.js
  back-end/package-lock.json
  back-end/package.json
  back-end/passport.js
  back-end/public/socials/ADA.json
  back-end/public/socials/BTC.json
  back-end/public/socials/DOGE.json
  back-end/public/socials/DOT.json
  back-end/public/socials/ETH.json
  back-end/public/socials/LTC.json
  back-end/public/socials/SHIB.json
  back-end/public/socials/SOL.json
  back-end/public/socials/crypto.json
  back-end/refreshNews.js
  back-end/refreshReddit.js
  back-end/refreshTwitter.js
  back-end/routes/getNews.js
  back-end/routes/getReddit.js
  back-end/routes/getTwitter.js
  back-end/routes/nfa.js
  back-end/routes/sentimentAnalysis.js
  back-end/routes/userAssetData.js
  front-end/src/containers/Dashboard/Dashboard.jsx
  front-end/src/containers/LandingPage/LandingPage.jsx
  front-end/src/containers/LoginPage/LoginPage.jsx
  front-end/src/containers/NFA/NFA.jsx
  front-end/src/containers/NewsPage/newsPage.jsx
Labels: enhancement

#166 add top bar and remove footer from pages
  back-end/app.js
  back-end/data.js
  back-end/public/timeSeriesData/SOL_11-22-2020_11-22-2021.json
  back-end/refreshNews.js
  back-end/refreshSocials/refreshNews.js
  back-end/refreshSocials/refreshReddit.js
  back-end/refreshSocials/refreshTwitter.js
  back-end/refreshSocials/validate.js
  back-end/routes/getNews.js
  back-end/routes/getReddit.js
  back-end/routes/getTwitter.js
  back-end/routes/userAssetData.js
  back-end/server.js
  back-end/test/getNews.test.js
  back-end/test/getSocials.test.js
  front-end/src/App.js
  front-end/src/components/Footer/footer.css
  front-end/src/components/Footer/footer.jsx
  front-end/src/components/Forms/AddAssetForm.jsx
  front-end/src/containers/Dashboard/Dashboard.jsx
  front-end/src/containers/LoginPage/LoginPage.jsx
  front-end/src/containers/NewsPage/newsPage.css
  front-end/src/containers/NewsPage/newsPage.jsx
  front-end/src/containers/ResetPasswordPage/ResetPassword.jsx
Labels: enhancement

#172 user email shows up in settings
  back-end/app.js
  back-end/passport.js
  front-end/src/containers/LoginPage/LoginPage.jsx
  front-end/src/containers/SettingsPage/SettingsPage.jsx
Labels: enhancement

#174 Persist logged in
  back-end/app.js
  back-end/appTest.spec.js
  back-end/db.js
  back-end/news.rest
  back-end/package-lock.json
  back-end/package.json
  back-end/refreshSocials/refreshNews.js
  back-end/refreshSocials/refreshReddit.js
  back-end/refreshSocials/refreshTwitter.js
  back-end/routes/coinPredict.js
  back-end/routes/coinPriceTimeSeries.js
  back-end/routes/getReddit.js
  back-end/routes/getTwitter.js
  back-end/routes/users.js
  back-end/server.js
  back-end/test/coinLabel.test.js
  back-end/test/coinPredict.test.js
  back-end/test/getNews.test.js
  back-end/test/getSocials.test.js
  back-end/test/sentimentAnalysis.test.js
  back-end/test/userAssetData.test.js
  back-end/test/wordcloud.test.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/PortfolioTable/PortfolioTable.jsx
  front-end/src/containers/Dashboard/Dashboard.jsx
  front-end/src/containers/LandingPage/LandingPage.jsx
  front-end/src/containers/LoginPage/LoginPage.jsx
  front-end/src/containers/NFA/NFA.jsx
  front-end/src/containers/ResetPasswordPage/ResetPassword.jsx
  front-end/src/containers/SettingsPage/SettingsPage.jsx
  front-end/src/notify.js
  front-end/src/worker.js
Labels: enhancement

#180 Add unit tests for socials and news
  back-end/package.json
  back-end/server.js
  back-end/test/getNews.test.js
  back-end/test/getSocials.test.js
  back-end/test/userAssetData.test.js
Labels: enhancement

#181 Fix front-end errors
  front-end/src/components/NFATable/NFATable.jsx
  front-end/src/containers/IndividualCoinPage/IndividualCoinPage.jsx
  front-end/src/containers/NFA/NFA.jsx
  front-end/src/containers/SignupPage/SignupPage.jsx
Labels: enhancement

#182 Fix all routes to pass tests
  back-end/app.js
  back-end/controllers/users.js
  back-end/routes/getReddit.js
  back-end/routes/getTwitter.js
  back-end/test/coinLabel.test.js
  back-end/test/coinLabelTest.js
  back-end/test/coinPredict.test.js
  back-end/test/coinPredictTest.js
  back-end/test/coinPresentPriceAndChange.test.js
  back-end/test/coinPresentPriceTest.js
  back-end/test/coinPriceTimeSeries.test.js
  back-end/test/coinTimePriceTest.js
  back-end/test/getNewsTest.js
  back-end/test/getSocials.test.js
  back-end/test/getSocialsTest.js
  back-end/test/mockdata.js
  back-end/test/routes.test.js
  back-end/test/sentimentAnalysis.test.js
  back-end/test/sentimentTest.js
  back-end/test/userAssetData.test.js
  back-end/test/userAssetTest.js
  back-end/test/wordcloud.test.js
  back-end/test/wordcloudTest.js
  front-end/src/components/NFATable/NFATable.jsx
  front-end/src/containers/LandingPage/LandingPage.jsx
  front-end/src/containers/LoginPage/LoginPage.jsx
  front-end/src/containers/NFA/NFA.jsx
Labels: enhancement
